using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class PlayerHealth : MonoBehaviour
{
    public int maxHealth = 100; // 최대 체력
    public int currentHealth; // 현재 체력

    public Slider healthBar; // HP 바 UI
    MonsterController Enemy;
    
    private void Start()
    {
        currentHealth = maxHealth;
        healthBar.maxValue = maxHealth;
        healthBar.value = currentHealth;
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Enemy"))
        {
            
            
            Debug.Log("공격에 맞음");
        }
    }

    


    public void TakeDamage1(int damage)
    {
        currentHealth -= damage;
        healthBar.value = currentHealth;

        if (currentHealth == 0)
        {
           
            Die();
        }
    }

    private void Die()
    {
        
    }
}
